name = "ci"
version = "0.1.0"

[dependencies]
cicd = "=0.9.0-pre.5"
distrib = "=0.9.0-pre.5"
fs = "=0.9.0-pre.5"
http = "=0.9.0-pre.5"
javascript = "=0.9.0-pre.5"
json = "=0.9.0-pre.5"
log = "=0.9.0-pre.5"
net = "=0.9.0-pre.5"
process = "=0.9.0-pre.5"
std = "=0.9.0-pre.5"
work = "=0.9.0-pre.5"

[entrypoints]
audit = "ci/github/build::audit"
benchmarks = "ci/github/build::benchmarks"
bogo = "ci/github/build::bogo"
build = "ci/workflows::buildEntrypoint"
checkExternalTypes = "ci/github/build::checkExternalTypes"
cifuzz = "ci/workflows::cifuzzEntrypoint"
clippy = "ci/github/build::clippy"
clippyNightly = "ci/github/build::clippyNightly"
connectTests = "ci/github/daily_tests::connectTests"
coverage = "ci/github/build::coverage"
cross = "ci/github/build::cross"
daily-tests = "ci/workflows::dailyTestsEntrypoint"
deploy = "ci/github/docs::deploy"
docs = "ci/workflows::docsEntrypoint"
exampleTests = "ci/github/daily_tests::exampleTests"
featurePowerset = "ci/github/daily_tests::featurePowerset"
features = "ci/github/build::features"
format = "ci/github/build::format"
formatUnstable = "ci/github/build::formatUnstable"
fuzz = "ci/github/build::fuzz"
fuzzing = "ci/github/cifuzz::fuzzing"
generate = "ci/github/docs::generate"
minver = "ci/github/build::minver"
msrv = "ci/github/build::msrv"
opensslTests = "ci/github/build::opensslTests"
semver = "ci/github/build::semver"
taplo = "ci/github/build::taplo"
