use cicd/services/github::replicateContextsWithInputs
use cicd/services/github::runAction
use javascript::JavaScriptEngine
use log/logger::Logger
use std/data/string_map::StringMap
use std/data/string_map::|entry
use std/data/string_map::|map
use std/ops/option::|wrap

#[github_action(obi1kenobi/cargo-semver-checks-action@v2)]
#[generated(true)]
treatment cargoSemverChecksAction[contexts: JavaScriptEngine, logger: Logger](
        var baseline_rev: string = "",
        var baseline_root: string = "",
        var baseline_version: string = "",
        var exclude: string = "",
        var feature_group: string = "",
        var features: string = "",
        var github_token: string = "${{ github.token }}",
        var manifest_path: string = "",
        var package: string = "",
        var prefix_key: string = "",
        var release_type: string = "",
        var rust_target: string = "",
        var rust_toolchain: string = "stable",
        var shared_key: string = "",
        var verbose: string = "false"
)
  input trigger: Block<void>
  output completed: Block<void>
  output continue: Block<void>
  output failed: Block<void>
  model node_contexts: JavaScriptEngine()
{
    mainAction: runAction[contexts = node_contexts, logger = logger](
        commands = "node .melodium-ci/github/actions/third/obi1kenobi/cargo_semver_checks_action/ref_v2/dist/index.js",
        env = |wrap<StringMap>(
        |map(
            [|entry(
                    "INPUT_PACKAGE",
                    package
                    ),
                |entry(
                    "INPUT_EXCLUDE",
                    exclude
                    ),
                |entry(
                    "INPUT_MANIFEST-PATH",
                    manifest_path
                    ),
                |entry(
                    "INPUT_FEATURE-GROUP",
                    feature_group
                    ),
                |entry(
                    "INPUT_FEATURES",
                    features
                    ),
                |entry(
                    "INPUT_VERBOSE",
                    verbose
                    ),
                |entry(
                    "INPUT_RELEASE-TYPE",
                    release_type
                    ),
                |entry(
                    "INPUT_RUST-TOOLCHAIN",
                    rust_toolchain
                    ),
                |entry(
                    "INPUT_RUST-TARGET",
                    rust_target
                    ),
                |entry(
                    "INPUT_SHARED-KEY",
                    shared_key
                    ),
                |entry(
                    "INPUT_PREFIX-KEY",
                    prefix_key
                    ),
                |entry(
                    "INPUT_GITHUB-TOKEN",
                    github_token
                    ),
                |entry(
                    "INPUT_BASELINE-VERSION",
                    baseline_version
                    ),
                |entry(
                    "INPUT_BASELINE-REV",
                    baseline_rev
                    ),
                |entry(
                    "INPUT_BASELINE-ROOT",
                    baseline_root
                    )]
            )
        ),
        name = "cargoSemverChecksAction"
    )
    replicateContextsWithInputs[action_contexts = node_contexts, main_contexts = contexts](
        inputs = |map(
        [|entry(
                "package",
                package
                ),
            |entry(
                "exclude",
                exclude
                ),
            |entry(
                "manifest-path",
                manifest_path
                ),
            |entry(
                "feature-group",
                feature_group
                ),
            |entry(
                "features",
                features
                ),
            |entry(
                "verbose",
                verbose
                ),
            |entry(
                "release-type",
                release_type
                ),
            |entry(
                "rust-toolchain",
                rust_toolchain
                ),
            |entry(
                "rust-target",
                rust_target
                ),
            |entry(
                "shared-key",
                shared_key
                ),
            |entry(
                "prefix-key",
                prefix_key
                ),
            |entry(
                "github-token",
                github_token
                ),
            |entry(
                "baseline-version",
                baseline_version
                ),
            |entry(
                "baseline-rev",
                baseline_rev
                ),
            |entry(
                "baseline-root",
                baseline_root
                )]
        )
    )

    Self.trigger -> replicateContextsWithInputs.trigger
    replicateContextsWithInputs.ready -> mainAction.trigger
    mainAction.completed -> Self.completed
    mainAction.failed -> Self.failed
    mainAction.continue -> Self.continue
}

